name = "Portfolio"
uuid = "7fcf9a35-b6d8-483f-b9b8-bc03cd463132"
authors = ["Mark Aron Szulyovszky <mark.szulyovszky@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
